name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Nếu bạn dùng Vite/Webpack:
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build   # tạo thư mục dist/

      # Nếu site thuần HTML/CSS/JS, KHÔNG build:
      # - run: |
      #     rm -rf dist && mkdir dist
      #     cp index.html dist/
      #     [ -d assets ] && rsync -a assets/ dist/assets/ || true
      #     [ -f favicon.ico ] && cp favicon.ico dist/ || true
      #     # KHÔNG copy src/

      # (khuyến nghị) xoá sourcemap để khó xem code
      - run: find dist -name "*.map" -delete

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist   # ✅ chỉ phát hành dist/

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
